### ISSUE TITLE
Position {x: 50, y: 50}, property 'y' not working

### ISSUE THREAD

**Issue by thegeett** [xieziyu/angular2-draggable#110]
Here for some reason draggable div is not position to 10,100. If I change x property then div moves accordingly but when I change y property it does not move.

`<div class='drag-container' #myBounds>
    <div class='drag-item1' [position]="position1" [bounds]='myBounds' [inBounds]="inBounds" ngDraggable>Drag me! (1)</div>`

public position1 = {x: 10, y: 100};

**Comment by xieziyu** [comment]
@thegeett 
Is the container's height less than `100 + div.height` ?

**Comment by thegeett** [comment]
Oh yes, that was the issue, Thank you. I gave container's height greater than `100 + div.height`.

**Comment by xieziyu** [comment]
Glad to know, closing this issue.
