### ISSUE TITLE
Control change detection with HostListener events

### ISSUE THREAD

**Issue by njofce** [xieziyu/angular2-draggable#112]
When a draggable component is active, a mousemove event listener is added and with each mouse move a change detection cycle is triggered. This is something that should be changed with the library, or provide means to run this outside of angular

**Comment by AlexJsNg** [comment]
Actually this is quite important issue on iPad. Guys how you solve or plan to solve it :) ?

**Comment by xieziyu** [comment]
Yes, it's a critical issue. I will fix it in the next release. Sorry about the late reply, I'm too busy recently.
