### ISSUE TITLE
Drag only along the x axis - both in negative and postive.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [xieziyu/angular2-draggable#129]
Hello, 
I am trying to make the div draggable only in the X axis. Both right and left side. I am doing it in a calendar so the events can be dragged. I am adding a grid step as well to jump to the days properly. But I am not able to find how to make it move only in the X axis. Please help me on that.

**Comment by xieziyu** [comment]
This could be a new feature to support. Currently, we can only use [boundary] and [inBounds].

**Comment by xieziyu** [comment]
@VigneshVaidyanathan 
`[lockAxis]` is supported in v2.2.0 now. Thanks.
