### ISSUE TITLE
Demo: Drag with touch

### ISSUE THREAD

**Issue by rufreakde** [xieziyu/angular2-draggable#13]
When I drag your Demo draggables with touch there is a problem with default browser behavior.
For e.g. it scrolls when I drag them down or up.

Demo: https://xieziyu.github.io/#/angular2-draggable/demo#demo2

Maybe you have to use: Event.preventDefault(); ?

**Comment by rufreakde** [comment]
Tried it out and it fixed my problem:
`  @HostListener('touchstart', ['$event'])
  onTouchStart(event: any) {
    event.stopPropagation();
    event.preventDefault();
    this.orignal = this.getPosition(event.changedTouches[0].clientX, event.changedTouches[0].clientY);
    this.pickUp();
  }

  @HostListener('document:touchmove', ['$event'])
  onTouchMove(event: any) {
    event.stopPropagation();
    event.preventDefault();
    if (this.moving && this.allowDrag) {
      this.moveTo(event.changedTouches[0].clientX, event.changedTouches[0].clientY);
    }
  }`

Issue:
But you can still dragg the window with touch, even if you only want the header to be the source for the dragg!

**Comment by rufreakde** [comment]
fixed that issue_
@HostListener('touchstart', ['$event'])
  onTouchStart(event: any) {
    event.stopPropagation();
    event.preventDefault();

    if (this.handle !== undefined && event.target !== this.handle) {
      return;
    }

    this.orignal = this.getPosition(event.changedTouches[0].clientX, event.changedTouches[0].clientY);
    this.pickUp();
  }

missing handler !

**Comment by rufreakde** [comment]
@xieziyu Sorry never made a Pull-Request before

> git pull-request v1.0.7 https://github.com/xieziyu/angular2-draggable.git

seems not to work. :(

**Comment by xieziyu** [comment]
@rufreakde I've merged your changes in v1.0.7, thanks again for your support. Will close this issue soon.
