### ISSUE TITLE
How to use method resetPosition in ts?

### ISSUE THREAD

**Issue by l-xue-yu** [xieziyu/angular2-draggable#136]
I find that  method resetPosition in doc,and there is a usage in demo.
![image](https://user-images.githubusercontent.com/42016055/50889027-e5a10980-1431-11e9-9521-c76a9a5a6df0.png)
The browser has a **error:Cannot read property 'resetPosition' of undefined**,when I use it in ts .I want to know how to use it.
![image](https://user-images.githubusercontent.com/42016055/50892243-00c34780-1439-11e9-86b0-cfad5bb8dec8.png)
I have get it .
![image](https://user-images.githubusercontent.com/42016055/50892346-36683080-1439-11e9-8af5-8d7eae3a01dc.png)

**Comment by xieziyu** [comment]
1. In your html, you should export `#videoContainer="ngDraggable"`

2. In your component, you can call methods of `videoContainer`
```typescript
this.videoContainer.resetPosition();
```

**Comment by l-xue-yu** [comment]
> 1. In your html, you should export `#videoContainer="ngDraggable"`
> 2. In your component, you can call methods of `videoContainer`
> 
> ```ts
> this.videoContainer.resetPosition();
> ```

My boss tell me how to get it. It should be like that @ViewChild("videoContainer") videoContainer: AngularDraggableModule;
其实我猜你也是国人。也许你可以在demo里说一下，像我这样的新手并不懂如何去获取这个元素……
最后，你的这个插件真的棒。

**Comment by xieziyu** [comment]
@l-xue-yu 
谢谢，解决就好。若有疑问直接发中文就好了～
