### ISSUE TITLE
ngResizable with not working properly when position has floating values

### ISSUE THREAD

**Issue by dioseltorre** [xieziyu/angular2-draggable#138]
Hi,

I used **ngDraggable** and **ngResizable** at the same time in our application. The app enables the user to drag and resize elements (div) anywhere inside a div containment and it has a `rzMinWidth` and `rzMinHeight` of **40**. With this, the position can have a floating values (e.g `translate(48.5px, 134.281px)`). The problem is when the position became a floating values and resize is performed, it will automatically resize to a given minimum values and you cannot resize it anymore unless you will drag it back to `0, 0` position.

I want to know if this is some kind of a bug.

Thanks.

**Comment by sergekk** [comment]
I run into same problem.

**ngDraggable** and **ngResizable** on same element caused problems if **bounds** input property set 
and browser zoom is not 100%.

Reason: getBoundingClientRect may return float values. See details here :
https://stackoverflow.com/questions/40879171/in-javascript-why-does-getboundingclientrect-sometimes-return-floating-point

Suggested fix: in AngularDraggableDirective.boundsCheck round values returned from getBoundingClientRect. For example : `this.tempTrans.y -= Math.round(elem.top) - Math.round(boundary.top);`

**Comment by dioseltorre** [comment]
fixed in this PR #151
