### ISSUE TITLE
Toggle [ngDraggable] while dragging

### ISSUE THREAD

**Issue by agnitos** [xieziyu/angular2-draggable#144]
If you toggle ngDraggable while you are dragging you get some wierd behaviour. If you start to drag while its set to true and change it to false while its dragging it will stop, but if you then set it to true it will jump it mouse location.
![drag-start-when-true](https://i.imgur.com/W4dopbi.gif)

I think this shouldn't work like this, if you set ngDraggable to false while you are dragging it should put the draggable down.

There is the similar issue when you start to drag when ngDraggable is set to false, it will update its position as if you are dragging when it gets set to true.
![drag-start-when-false](https://i.imgur.com/noDH84b.gif)

It shouldn't start to drag if ngDraggable is set to false.

**Comment by xieziyu** [comment]
Thanks
