### ISSUE TITLE
Problem resizing with containment

### ISSUE THREAD

**Issue by RaananW** [xieziyu/angular2-draggable#159]
Hi,

Thanks for a great plugin :-)
I am having a problem, which i thought is due to my setup, but then i found out it is also present in the example page. Here is a quick screencast:
![Angular2DraggableDemo - Edited](https://user-images.githubusercontent.com/1381702/56970650-de7c4380-6b67-11e9-91ae-11dd3ca6a98c.gif)

There are two problems presented here:

1) The left / width values keep on bouncing when on the lower edge of the container
2) The right side of the container doesn't stop from resizing.

It seems to be related to the checkBounds function and the correlation to origSize, but i still haven't found the concrete reason. Any idea how to fix this?

**Comment by xieziyu** [comment]
Thanks for reporting this issue. I will look into it.

**Comment by RaananW** [comment]
Amazing, thanks a lot for a quick fix!

**Comment by dioseltorre** [comment]
I found the same issue but using **nw** and **sw** handles. This is using the latest version (2.3.0) as of this writing.
As you can see below:

![screen-capture-_3_](https://user-images.githubusercontent.com/14935048/58076799-123a0e80-7be6-11e9-8a41-00d7d29bee6e.gif)
