### ISSUE TITLE
Is there a way to constrain in an elment?

### ISSUE THREAD

**Issue by nickyxu** [xieziyu/angular2-draggable#16]
Hi,
   I found ng2-movable module. 
It has the feature which constrain the movable <div> to an elment.

Take a look at website:
https://spali.github.io/ng2-movable/
 
Could we implement the same feature?

Cheers,
Nicky

**Comment by xieziyu** [comment]
Thanks for your suggestion. This feature is supported in v1.1.0-beta.0. Please refer to the demo page.
