### ISSUE TITLE
feature request: add CSS class when dragging is in progress

### ISSUE THREAD

**Issue by danday74** [xieziyu/angular2-draggable#163]
Currently, the CSS class ng-draggable is added to any draggable elements.

It would be great if the class ng-dragging could also be added during a drag operation. This would allow styling for the cursor during a drag operation:

```
.ng-draggable {
  cursor: grab;
}

.ng-dragging {
  cursor: grabbing;
}
```
Great lib thx :)

**Comment by xieziyu** [comment]
Thanks for your suggestion. I will make it work.

**Comment by danday74** [comment]
thanks for the quick turn around - please could you advise when this is released to npm

**Comment by xieziyu** [comment]
@danday74 
It's already published in 2.3.0

**Comment by danday74** [comment]
many thanks :) this is a great feature

**Comment by lucadln** [comment]
Hi @xieziyu ,

Any chance I can make this work for resizing as well?

Thank you, 
Lucian.
