### ISSUE TITLE
Resize doesn't work on Windows10 IE11 (and on some windows 7 IE11)

### ISSUE THREAD

**Issue by LiorSaadon** [xieziyu/angular2-draggable#164]
I'm using Angular 7 and angular2-draggable 2.2.4 (i also tried older versions)
and the resize doesn't work.

Easiest way to repreduce it is try using the demo provided by the xieziyu here: https://xieziyu.github.io/angular2-draggable/#/resizable/events

On Windows 10 + IE11 the resize just doesn't work.

On Windows7 + IE11 it works on some machines (i can't tell the difference they all have the same version but some work and some just don't)

please fix it :)

**Comment by jaa1982** [comment]
yes can you please look investigate ? unfortunately we are also still required to support IE11 , and we would love to be able to use this excellent module

**Comment by xieziyu** [comment]
Thank you for reporting this issue. I need some time to investigate it. Any help could be grateful and thanks for your supports.

**Comment by LiorSaadon** [comment]
still not working, but after debugging i found the fix, i will create a pull request for you
