### ISSUE TITLE
Drag not working when dynamically setting transform

### ISSUE THREAD

**Issue by gouravlath** [xieziyu/angular2-draggable#182]
Hi
We are using this great plugin in our project. The problem I am facing is when we dynamically change transform of a draggable div and try to drag the div, the div is getting first dragged to old drag position and then allowing drag. Please help us out.

**Comment by xieziyu** [comment]
@gouravlath 
Can you try to use `[position]` instead of setting transform?

**Comment by gouravlath** [comment]
Hi
Thanks. Using [position] works like charm.
