### ISSUE TITLE
Limit the drag zone

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [xieziyu/angular2-draggable#19]
Could be possible if we can limit the drag zone by a parent div or by pixels?
For example: I want to limit zone of the draggable to the #oMap

```
<o-map #oMap zoom="11" min-zoom="3" max-zoom="20" zoom-control="yes" search-control="yes" draw-control="no" layer-panel-visible="false" base-layer-ids="OpenStreetMap">    
</o-map>

<div ngDraggable>
drageMe
</div>
```

Thanks.

**Comment by xieziyu** [comment]
This feature is supported in v1.1.0-beta.0. Please refer to the demo page.
