### ISSUE TITLE
Observable of Being Dragged

### ISSUE THREAD

**Issue by ThisGuyRghtHereee** [xieziyu/angular2-draggable#2]
Ability to tell whether or not something is being dragged.

**Comment by xieziyu** [comment]
@ThisGuyRghtHereee Thanks. `started` and `stopped` events are supported in v1.0.3

**Comment by ThisGuyRghtHereee** [comment]
Please add an example for using nativeElements

**Comment by ThisGuyRghtHereee** [comment]
Here is my simple boolean example:
**angular2-draggable.component.ts**
`import { Component } from '@angular/core';

@Component({
  selector: '',
  templateUrl: './angular2-draggable.component.html',
  styleUrls: ['']
})
export class Angular2DraggableComponent {

  isBeingDragged: boolean = false;

  constructor() { }

  startDrag() {
    /* do stuff */
  }

  endDrag() {
    /* do stuff */
  }
}
`

**angular2-draggable.component.html**
`<div ngDraggable [handle]="handle" (started)="startDrag()" (stopped)="endDrag()" style="float: left; position: fixed; top: 50%; left: 50%; min-width: fit-content">
  <div style="position: relative; top: -50%; left: -50%">
    <div #handle style="box-shadow: 2px 2px 5px grey">
      Test Draggable Div
    </div>
  </div>
</div>`

_Please correct if I made any mistakes_

**Comment by xieziyu** [comment]
@ThisGuyRghtHereee 
Example to use the nativeElement:

```html
<div id="demo" ngDraggable (started)="startDrag($event)" (stopped)="endDrag($event)"></div>
```

```javascript
startDrag(el) {
  console.log('start to drag element: ', el.id);
}
```
