### ISSUE TITLE
this.bounds is undefined by default

### ISSUE THREAD

**Issue by nm-a** [xieziyu/angular2-draggable#20]
Hi,
I see this.bounds = undefined by default. I have added below code to fix it. Can you recommend that is there any alternative.

`    private boundsCheck() {        
        if (this.bounds == undefined || this.bounds == null) {
            this.bounds = this.el.nativeElement.parentElement;
        }
        let boundary = this.bounds.getBoundingClientRect();
        let elem = this.el.nativeElement.getBoundingClientRect()
        return {
            'top': boundary.top < elem.top,
            'right': boundary.right > elem.right,
            'bottom': boundary.bottom > elem.bottom,
            'left': boundary.left < elem.left
        };
    }`

thank you

**Comment by xieziyu** [comment]
@nm-a Thanks for reporting this issue. This should be fixed in v1.1.0-beta.0
