### ISSUE TITLE
Add support for keep dragged div within bounds

### ISSUE THREAD

**Issue by ThisGuyRghtHereee** [xieziyu/angular2-draggable#4]
Snap div back within bounds if dragged outside.
(parent div, defined area/size, browser window, etc.)

**Comment by boom235** [comment]
I tried to implement this myself by changing the CSS in 

> (stopped)="onDragEnd($event)"

It works but has some strange behaviour when picking it up again... So this feature would be awesome, yeah!

`private onDragEnd(box: any) {
        let screensize = window.screen,
            curPosX = 0,
            curPosY = 0;
        
        try {
            // get current pos out of css
            let curPos = box.style.transform.split('(')[1].split(')')[0].split(', ');
            curPosX = Math.abs(curPos[0].split('px')[0]);
            curPosY = Math.abs(curPos[1].split('px')[0]);

            if(
                curPosX + 55 > (screensize.width/2) ||
                curPosY + 55 > (screensize.height/2)
            ) {
                // outside of window, reset to middle
                let value = "translate(" + 0 + "px, " + 0 + "px)";
                box.style.transform = value;
                box.style.webkitTransform = value;
                box.style.MozTransform = value;
                box.style.msTransform = value;
                box.style.OTransform = value;
                box.style['-moz-transform'] = value;
                box.style['-ms-transform'] = value;
                box.style['-o-transform'] = value;
            }
        } catch(ex) {
            console.log('transformation failed');
        }
    }`

**Comment by xieziyu** [comment]
@boom235 Thanks for your support. Now I have new implementation in v1.1.0-beta.0
