### ISSUE TITLE
not able to disable

### ISSUE THREAD

**Issue by reinierstam** [xieziyu/angular2-draggable#5]
when ngDraggable is set to false my element is still dragable.

**Comment by xieziyu** [comment]
@reinierstam Can you share your codes? In my demo page, I did disable the directive.

**Comment by reinierstam** [comment]
`<svg #circle class='draggable' [attr.height]="editingSize.height" [attr.width]="editingSize.width" [style.position]="'absolute'" [style.left]="xpos" [style.top]="ypos"
   ngDraggable=''false'' (click)="onDrag($event, sensor)">
  <circle [popover]="myPopover" [popoverOnHover]="true" [attr.cx]="editingSize.cx" [attr.cy]="editingSize.cy" [attr.r]="editingSize.r" stroke="black" stroke-width="1" [attr.fill]="sensorStatusColor" />
</svg>`

and i imported in my app.module.ts like this:
`import { AngularDraggableModule } from 'angular2-draggable';`
(and added it to the imports ofc).

**Comment by xieziyu** [comment]
@reinierstam OK, I know. You've set a string 'false' which is not a boolean value to ngDraggable.

**Comment by ThisGuyRghtHereee** [comment]
`<svg #circle class='draggable' [attr.height]="editingSize.height" [attr.width]="editingSize.width" [style.position]="'absolute'" [style.left]="xpos" [style.top]="ypos" ngDraggable="{{false}}" (click)="onDrag($event, sensor)"> <circle [popover]="myPopover" [popoverOnHover]="true" [attr.cx]="editingSize.cx" [attr.cy]="editingSize.cy" [attr.r]="editingSize.r" stroke="black" stroke-width="1" [attr.fill]="sensorStatusColor" /> </svg>`

Your quotes are a bit confusing..

**Comment by OctavioSI** [comment]
I had to use `[ngDraggable]="booleanSetOnYourComponent"` to make it disable movement.
