### ISSUE TITLE
Not able to drag to left or right if I use bounds

### ISSUE THREAD

**Issue by aadeshkranderia** [xieziyu/angular2-draggable#56]
Hi,

I followed the instructions you gave in the demo but I am not able to drag my element to left or right. Only top and bottom movement works. Also, if I set inBounds = false, it works as expected. Please let me know where I might be making a mistake. Thanks

**Comment by xieziyu** [comment]
Maybe your bounds div has the same width with your draggable div.

**Comment by aadeshkranderia** [comment]
Yes. I got that fixed. Forgot to close the issue. Thanks!
