### ISSUE TITLE
Allow an element to get out of bound

### ISSUE THREAD

**Issue by waldo2188** [xieziyu/angular2-draggable#57]
Hi,

Actual :
We use angular2-draggable with ng-bootstrap modal module.
We fix bound to be sure that the modal don't go out of the viewport.

Needed:
We need to be able to allow the modal to go out of the bottom edge.
Cause some of our modal are huge and we need to push it to the bottom to see what's behind (like Windows/Linux/Mac OS)

I will make you a pull request to show what I have in mind.

Great work, by the way.

**Comment by xieziyu** [comment]
Thanks for your great support!

**Comment by waldo2188** [comment]
You're welcome ;)
