### ISSUE TITLE
Custom z-index

### ISSUE THREAD

**Issue by ThisGuyRghtHereee** [xieziyu/angular2-draggable#6]
Some draggable windows should be underneath other objects such as modals. Forcing a z-index of 99999 doesn't allow this.

**Comment by xieziyu** [comment]
@ThisGuyRghtHereee z-index will be restored after dragging.

**Comment by ThisGuyRghtHereee** [comment]
Z-index works some of the time, but it does have a bug of getting set to 99999 and not restoring.
![image](https://user-images.githubusercontent.com/8634442/27093603-3812e124-501c-11e7-9576-3e923e95bfb9.png)

I have a z-index of 1000 set, but every other time I refresh my browser it gets set to auto, then sticks at 99999.

Can there be a toggle to not allow the z-index to be changed? Why is it set to 99999 when dragging?

**Comment by earthican** [comment]
+1
In my use case, I have a component's `z-index` set to `-1`, but it gets set to `auto` after dragging ends.

**Comment by xieziyu** [comment]
Thanks for your suggestions. This feature is supported in v1.1.0-beta.0. Please use [zIndex] and [zIndexMoving] to handle it. You can refer to demo page for details.
