### ISSUE TITLE
Bad positioning when multiple draggable elements in one container

### ISSUE THREAD

**Issue by erwsub** [xieziyu/angular2-draggable#67]
If there are multiple draggable elements in the container only the first one is positioned correctly. The second ones y coordinate is not relative to the container.

```
public position1 = {x: 10, y: 10};
public position2 = {x: 150, y: 10};
```

```
<div class='drag-container' #myBounds>
    <div class='drag-item1' [position]="position1" [bounds]='myBounds' [inBounds]="inBounds" ngDraggable>Drag me! (1)</div>
    <div class='drag-item2' [position]="position2" [bounds]='myBounds' [inBounds]="inBounds" ngDraggable>Drag me! (2)</div>
</div>
```

![screenshot_20180508_091103](https://user-images.githubusercontent.com/20328485/39743227-8f9eb56c-52a0-11e8-95b9-2e8bbd70cdd9.png)

**Comment by xieziyu** [comment]
@erwsub Please try to add `position: relative` to container and `position: absolute` to the item blocks.

**Comment by erwsub** [comment]
Yes. That was missing. Thank you.
