### ISSUE TITLE
Unable to get the started and stopped events to work.

### ISSUE THREAD

**Issue by nayanita** [xieziyu/angular2-draggable#7]
My code is as follows:

HTML
"<div ngDraggable class="col col-lg-4 col-md-4 col-sm-4 visuaItem"  *ngFor="let chartItem of availableCharts; let i = index;" [ngClass]="{'showItem': chartItem.isAvailable == true}" (mousedown)="onEvent($event)" (started)="onDragBegin($event)">"

JS

onDragBegin(event){
  		alert("HI");
  	}
  	
  	
  onEvent(event) {
   event.stopPropagation();
   this.flag=true;
}

Could you please tell me where I am going wrong? Any help would be highly appreciated.

**Comment by xieziyu** [comment]
@nayanita I tested similar codes and I can't reproduce your issue. I think the lines you posted are correct. Would you please show more of them?

**Comment by nayanita** [comment]
these are the only lines having the (started)="onDragBegin($event)">"

Also could you please advise if we have any such feature in angular2 by which we can draw connecting lines between 2 draggable divs?

**Comment by ThisGuyRghtHereee** [comment]
I have my code structured like this:
`<div ngDraggable [handle]="handle" (started)="startDrag()" (stopped)="endDrag()">Content</div>`
HTML

`startDrag() {
    this.isDragging = true;
  }`

  `endDrag() {
    this.isDragging = false;
  }`
TS

I know it's chunky, but it's working for me.

**Comment by lafiza** [comment]
can we have this draggable property for a modal popup ?
I am using ngx-modal to create a modal popup

**Comment by ThisGuyRghtHereee** [comment]
@lafiza Create a new issue. This is a different topic.
