### ISSUE TITLE
Boundary Check in Responsive Web not triggered

### ISSUE THREAD

**Issue by teohhc** [xieziyu/angular2-draggable#71]
Hi,

Using with Angular Layout for responsive web. I've create a div in that container which will automatically resize from landscape to portrait. A div containing menu will also appear at the top rather than side. The draggable div doesn't resize correctly and is out of its boundary due this. But when I click on the draggable div, it will instantly re-correct itself into the boundary again. It would be great if it doesn't need clicking to trigger that boundary check.
![draggable](https://user-images.githubusercontent.com/7022124/40408840-7a05d756-5e9b-11e8-9919-cd014e62ab9a.png)

Thank you.

**Comment by xieziyu** [comment]
@teohhc OK, I exposed boundsCheck() method in v1.4.2. Now you can use it to adjust position automatically when window resized.
```typescript
@ViewChild(AngularDraggableDirective) dragMe: AngularDraggableDirective;

@HostListner('window:resize')
onWindowResize() {
  this.dragMe.boundsCheck();
}
```

**Comment by teohhc** [comment]
Thank you,  I've just tested and it is working nicely now.
