### ISSUE TITLE
angular2-draggable Metadata version mismatch for version 2.0.0-beta.1

### ISSUE THREAD

**Issue by nileskh16** [xieziyu/angular2-draggable#75]
I'm using this module for an angular 4 application, 
'angular/cli: 1.3.2'
'angular/compiler-cli: 4.3.6 '
The module is working fine unless I do a AOT build, and exactly as a result of AOT build, the build fails due spitting out an error "metadata version mismatch for module angular2-draggable found version 4, expected 3". Seems like, the module was built with angular 5+ as it introduced the metadata version 4. 
Please assist in this scenario or at least suggest the lower version to which I can safely downgrade the module to without breaking my functionality.

**Comment by xieziyu** [comment]
@nileskh16 
Yes, it's a compatibility issue. I need to update the README. Thanks.

If you only need ngDraggable directive, you can downgrade to v1.4.2.
If you need ngResizable directive, I'm afraid you need move on to angular 5+.

**Comment by nileskh16** [comment]
@xieziyu 
Thanks a lot mate, it precisely resolved my build issue but I'm still wondering why I won't be able to use ngResizable directive in Angular 4 app.
Anyway, thanks for instant reply and I hope Resizable directive is made available in future. I would be so delighted to know that.
