### ISSUE TITLE
Change detection triggered everytime on mousemove

### ISSUE THREAD

**Issue by rathodsanjay** [xieziyu/angular2-draggable#77]
I am using angular2-draggable on a dynamically created component. As soon as the component gets rendered, the mousemove event binds to the document and is called on every single mouse movement. This triggers change detection and causes severe performance issues.

It seems better to have an option to bind mouse move event to the 'bounds' element rather than document. Or if we can use observables instead of hostlisteners? One other way around is to use runOutsideAngular. Not sure which will fit in this scenario.

**Comment by jaouenk** [comment]
Any information about it ?

**Comment by rathodsanjay** [comment]
Nope. Also, there is a similar issue logged by another user: #112 so, I am closing this. And we can continue the conversation there.
