### ISSUE TITLE
how to configure angular2-draggable with systemJS

### ISSUE THREAD

**Issue by xialiao** [xieziyu/angular2-draggable#8]
Hi, I have tried to configure angular2-draggable in my application's system.config.js without success. The config file has lines like following,

map {
...
'angular2-draggable': 'npm:angular2-draggable',
...
},
packages {
...
'angular2-draggable':  { 
        main: 'index.js',  
        format: 'cjs',
        defaultExtension: 'js' 
      }
...
}

Can you please advise?

Thanks!

**Comment by xieziyu** [comment]
@xialiao I need to publish angular2-draggable in UMD format, so that SystemJS could load it correctly. I'm afraid you could not import angular2-draggable until then.

**Comment by xieziyu** [comment]
@xialiao Please update to v1.0.4 and follow the instruction in README to configure systemjs.

**Comment by xialiao** [comment]
Worked like a charm, thank you very much!

**Comment by xialiao** [comment]
I also want to say this is a very useful library. We have a few modals in our software that were in fixed position, with this library, I can easily make them all draggle. The library is very convenient, thanks!
