### ISSUE TITLE
Drag & Resize on an image

### ISSUE THREAD

**Issue by gygabyte017** [xieziyu/angular2-draggable#80]
I need to insert an <img> where the user can drag it around with the mouse and resize it dragging its borders.

What I have done:
```
<div class="row">
    <div class="col-12" #imageBoundary>
        <img ngDraggable [preventDefaultEvent]="true" [zIndex]="10" [bounds]="imageBoundary" [inBounds]="true"
            ngResizable
            src="assets/drag.jpg" >
    </div>
</div>
```

The ngDraggable part is working correctly, I can move the image around within boundaries.
The ngResizable is not working, I can't even see the bottom right anchor arrow.

**Comment by xieziyu** [comment]
Did you add `resizable.min.css` in your project?

**Comment by gygabyte017** [comment]
Yes sorry I forgot to mention. `resizable.min.css` is added directly to `angular.json` styles section.

However the same example works on a div (like in your demo), so there seems to be something related to img.

**Comment by xieziyu** [comment]
@gygabyte017 
<img> is an empty element, so ngResizable can't add any child nodes. I think you can try to use a resizable container div to make it work.

**Comment by gygabyte017** [comment]
I understand, so I moved the draggable logic into a div (which has the img inside) and it works great!
