### ISSUE TITLE
当被拖拽元素到达边界时

### ISSUE THREAD

**Issue by qq1209974887** [xieziyu/angular2-draggable#85]
当被拖拽元素越过边界时，被拖拽元素的偏移量仍在持续计算中而无法阻止，即拖拽提前结束并停止偏移量计算

**Comment by xieziyu** [comment]
@qq1209974887 是否没有开启[inBounds]属性？

**Comment by qq1209974887** [comment]
我想着在这个时候是否可以阻止整个拖拽事件，如果能够抛出mousemove事件的$event，我想可以阻止，但现在不可以

**Comment by xieziyu** [comment]
@qq1209974887 
1. 我们并不能在到达边界的时候去阻止拖拽事件，这样会导致元素停在那拖不回来，很奇怪的行为。
2. 开启inBounds属性后，拖拽元素是不会越过边界的，这样的话偏移量也不会溢出。这里，我不是很明白你要阻止偏移量计算的原因是什么？

**Comment by qq1209974887** [comment]
@xieziyu 谢谢。这个问题已解决了，我原先没有看明白，可能没有理解清楚
