### ISSUE TITLE
Buttons stop working when upgraded to stable version

### ISSUE THREAD

**Issue by ArthurBrito** [xieziyu/angular2-draggable#87]
I am using version "2.0.0-beta.2" and when I updated to version 2.0.0 my buttons of minimizing and exiting stop working in my iframes.

**Comment by bponder** [comment]
likely related, all of my buttons are now non-functioning inside of a dynamic generated component using version 2.0.0

**Comment by ArthurBrito** [comment]
I am also using a dynamically generated component, don't know if it is important. For now, I just set my version to 2.0.0-beta.2 in my package.json

**Comment by xieziyu** [comment]
@ArthurBrito 
Please update to v2.0.1.
