### ISSUE TITLE
Not compiling after installing angular2-draggable

### ISSUE THREAD

**Issue by Adambs** [xieziyu/angular2-draggable#88]
ERROR in node_modules/angular2-draggable/lib/angular-resizable.directive.d.ts(62,21): error TS2315: Type 'ElementRef' is not generic.

**Comment by Adambs** [comment]
{
  "name": "shiftscraft",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.0.1",
    "@angular/cdk": "5.0.0-rc0",
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/material": "5.0.0-rc0",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@angular/router": "5.0.1",
    "@asymmetrik/ngx-leaflet": "^2.5.1",
    "@ngx-translate/core": "9.1.1",
    "@ngx-translate/http-loader": "2.0.1",
    "@swimlane/ngx-datatable": "11.0.4",
    "@zerohouse/router-tab": "0.0.3",
    "amazing-time-picker": "^1.5.3",
    "angular-calendar": "0.21.3",
    "angular-material-clock-time-picker": "0.0.9",
    "angular-tree-component": "5.2.1",
    "angular2-draggable": "^2.0.1",
    "ap-angular2-fullcalendar": "^1.3.7",
    "chart.js": "2.7.1",
    "core-js": "2.5.1",
    "d3": "4.11.0",
    "debounce": "^1.1.0",
    "dragula": "3.7.2",
    "fullcalendar": "^3.6.1",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "jquery": "^3.2.1",
    "jwt-decode": "^2.2.0",
    "leaflet": "1.2.0",
    "moment": "^2.19.2",
    "moment-timezone": "^0.5.14",
    "ng2-charts": "1.6.0",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "1.2.1",
    "ng2-validation": "4.2.0",
    "ngx-color": "^1.1.1",
    "ngx-perfect-scrollbar": "5.0.0",
    "ngx-quill": "2.0.4",
    "ngx-spinner": "^6.0.0",
    "randomcolor": "^0.5.3",
    "rxjs": "5.5.2",
    "screenfull": "3.3.2",
    "socket.io": "^2.0.4",
    "socket.io-client": "^2.0.4",
    "title-case": "^2.1.1",
    "zone.js": "0.8.10"
  },
  "devDependencies": {
    "@angular/cli": "^6.1.2",
    "@angular/compiler-cli": "5.0.1",
    "@angular/language-service": "5.0.1",
    "@types/google.analytics": "0.0.36",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.7",
    "@types/node": "^6.0.95",
    "@types/socket.io-client": "^1.4.32",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2",
    "@angular-devkit/build-angular": "~0.6.8"
  },
  "postinstall": "rm -Rf ./node_modules/app-angular2-fullcalendar/node_modules"
}

**Comment by xieziyu** [comment]
@Adambs 
angular2-draggable v2.x requires Angular 6. Please install `angular2-draggable@1.4.2`

**Comment by Adambs** [comment]
Works ! great support so quick 
tnx xieziyu
