### ISSUE TITLE
Only appears to work in Chrome

### ISSUE THREAD

**Issue by bodom0015** [xieziyu/angular2-draggable#9]
In Chrome 58 / 59, this module works as expected.

In other browsers, I am getting variants of the same error:
* Safari 10: 
> Can't find variable TouchEvent
* Firefox 53 / 54: 
> TouchEvent is not defined

Removing references to angular2-draggable in my project caused these errors to disappear.
Any idea what's going on here? Have I perhaps done something wrong in the setup?

**Comment by laps1967** [comment]
I'm experiencing the same issue with IE 11, I am just testing the demo, it works with Chrome but not in IE.

**Comment by xieziyu** [comment]
@laps1967 I used `window.getComputedStyle` in my code. It's not working in IE 11 as I expected. I should work out another solution for this.

@bodom0015 I think the error for the `TouchEvent` is another issue. Did you use `.umd` bundle or not?

**Comment by laps1967** [comment]
thank you so much xieziyu, I see the demo is now working for me in IE 11, I will get the latest version and will try this in my project, very excited about this new feature :)

**Comment by bodom0015** [comment]
Yes, I followed the instructions here: https://www.npmjs.com/package/angular2-draggable

Using `"angular2-draggable": "1.0.4"`, my `systemjs.config.js` is as follows:
```javascript
(function(global) {
  System.config({
    warnings: true,
    paths: {
      'npm:': 'node_modules/',
      
      'systemjs': 'node_modules/systemjs/dist/system.js',
      'system-polyfills': 'node_modules/systemjs/dist/system-polyfills.js',
      'es-module-loader': 'node_modules/es6-module-loader/dist/es-module-loader.js',
      'traceur': 'node_modules/traceur/bin/traceur-runtime.js',
    },
    map: {
      'dist': 'dist',
      'src': 'src',
      
      'angular2-jwt': 'npm:angular2-jwt/angular2-jwt.js',
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',

      'file-saver': 'npm:file-saver/FileSaver.min.js',
      'rxjs': 'npm:rxjs',
      
      'moment': 'npm:moment/moment.js',
      'ngx-bootstrap': 'npm:ngx-bootstrap/bundles/ngx-bootstrap.umd.js',
      'ng2-slimscroll': 'npm:ng2-slimscroll/bundles/ng2-slimscroll.umd.js',
      'ng2-file-upload': 'npm:ng2-file-upload/bundles/ng2-file-upload.umd.js',
      'angular2-draggable': 'npm:angular2-draggable',
      
      crypto: '@empty'
    },
    packages: {
      
      // TypeScript source
      'src': {
        defaultExtension: 'ts'
      },
      
      // Transpiled JavaScript
      'dist': {
        defaultExtension: 'js'
      },
      
      'rxjs': {
        defaultExtension: 'js'
      },
      
      'file-saver': {
        format: "cjs"
      },
      
      'moment': { 
        defaultExtension: 'js'
      },
      
      'ngx-bootstrap': { 
        defaultExtension: 'js'
      },
      
      'ng2-slimscroll': {
        defaultExtension: 'js'
      },
      
      'ng2-file-upload': {
        defaultExtension: 'js'
      },
      
      'angular2-draggable':  { 
        defaultExtension: 'js',
        main: 'bundles/angular2-draggable.umd.min.js'
      }
    }
  })
})(this);
```

Then, in my module:
```typescript
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {AngularDraggableModule} from 'angular2-draggable';

import {Footer} from './Footer';
import {TagEditorModal} from './TagEditorModal';
import {TextboxEditorModal} from './TextboxEditorModal';
import {MyModal} from './MyModal';
import {MyOtherModal} from './MyOtherModal';

@NgModule({
    imports: [CommonModule, FormsModule, AngularDraggableModule],
    declarations: [Footer, TagEditorModal, TextboxEditorModal, MyModal, MyOtherModal],
    exports: [Footer, TagEditorModal, TextboxEditorModal, MyModal, MyOtherModal]
})

export class MyTestModule { }
```

And in my component template(s):
```html
<div class="my-modal" ngDraggable>
      Modal content
</div>
```

Does the above configuration seem correct to you?

**Comment by xialiao** [comment]
We had similar issue with Firefox and Safari when using this package. We did a little research and realized Firefox and Safari at the time did not support TouchEvent, see Browser Compatibility at https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent.

**Comment by bodom0015** [comment]
Hi, @xialiao! This is Mike Lambert from the KnowEnG project! :D 

I was just raising this issue with the package developer to see if they recognized the error, or could offer any insight.

**Comment by xieziyu** [comment]
@xialiao Yes, you are right. I used `TouchEvent` just for mobile phones and its definition is not supported by FF and Safari. I realized that mistake, so I removed the definition in v1.0.5. 

@bodom0015 please use v1.0.5, It should work in FF and Safari. : )

**Comment by bodom0015** [comment]
Awesome, that totally fixed it! Thank you so much for the help!! :D

Closing this issue
