### ISSUE TITLE
Npm package license

### ISSUE THREAD

**Issue by BradleyHill** [xieziyu/angular2-draggable#92]
Here is says your MIT license. Npm lists you as `none`. License checker reports: `Custom: https://badge.fury.io/js/angular2-draggable.svg`

Any chance of adding `"license": "MIT"` entry to the package json. Thanks

**Comment by wcroteau** [comment]
It would seem that this issue has reoccured as the license was obliterated on this checkin:
https://github.com/xieziyu/angular2-draggable/commit/050e3f7150c262116b74c2ee55b9595ab19c136a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Any chance of re-instating it?
