### ISSUE TITLE
resizing from w, nw or n with a min/max size moves the window if it goes below/above the min/max size

### ISSUE THREAD

**Issue by kukelekuuk00** [xieziyu/angular2-draggable#94]
I've got a gfy showing off what it does, https://gfycat.com/ConfusedZanyAnaconda

**Comment by xieziyu** [comment]
@kukelekuuk00 
Yes, I will fix it.

**Comment by xieziyu** [comment]
@kukelekuuk00 
I've published `2.1.1` to fix this issue. Please let me know if there is any more question. Thank you.

**Comment by kukelekuuk00** [comment]
Works perfectly now. Thanks!
